### PR TITLE
Update CHANGELOG for 1.0

### PR DESCRIPTION
**Pull request by JelleZijlstra**

### CODE REVIEW

**Comment by LiraNuna** [comment]
* `dict`s can now be `yield`ed

**Comment by LiraNuna** [comment]
When will 1.0 be released?

Currently we have to use this hack to yield dicts:

```python
@asynq.async()
def gen_dict(dict_future):
    """
    Currently, asynq has a bug where we can't yield dicts without destroying batching.
    This method yields lists then merges them into a dict to allow us to generate a dict
    """

    items = list(dict_future.items())
    keys = [key for key, value in items]
    values = yield [value for key, value in items]

    return dict(zip(keys, values))
```

The performance boost and new debugging option would also be appreciated.

**Comment by JelleZijlstra** [comment]
Hopefully soon, I'd like to get #40 merged first.

**Comment by JelleZijlstra** [comment]
Relatedly, @LiraNuna would you be able to test the master version of asynq to make sure that we're not introducing any regressions in your codebase?

**Comment by LiraNuna** [comment]
I've been meaning to post an issue about this but for some reason we can't install asynq that is not published in pip. We get:

```
Obtaining asynq from git+https://github.com/quora/asynq.git@94ce4eecde95b6289dd8122270764ded8fbddbf5#egg=asynq (from -r requirements.txt (line 4))
  Skipping because already up-to-date.
No files/directories in /home/liranuna/Projects/webdev/py/patreon_py/venv/src/asynq (from PKG-INFO)
```

when using 

```pip install -e git+https://github.com/quora/asynq.git@94ce4eecde95b6289dd8122270764ded8fbddbf5#egg=asynq```

**Comment by JelleZijlstra** [comment]
Try adding `--upgrade --force-reinstall`? I don't think this is specific to asynq.

**Pull request merged**
